name: Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: pgvector/pgvector:pg15
        env:
          POSTGRES_DB: ragdb
          POSTGRES_USER: raguser
          POSTGRES_PASSWORD: changeme
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        env:
          REDIS_PASSWORD: changeme
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      minio:
        image: minio/minio:edge-cicd
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        ports:
          - 9000:9000
          - 9001:9001
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live"
          --health-interval 30s
          --health-timeout 20s
          --health-retries 3
        volumes:
          - /tmp/minio-data:/data

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      working-directory: ./server
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx

    - name: Wait for services to be ready
      run: |
        # Wait for PostgreSQL
        until pg_isready -h localhost -p 5432 -U raguser; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        
        # Wait for Redis
        until redis-cli -h localhost -p 6379 ping; do
          echo "Waiting for Redis..."
          sleep 2
        done
        
        # Wait for MinIO (simplified check)
        until curl -f http://localhost:9000/minio/health/live; do
          echo "Waiting for MinIO..."
          sleep 5
        done

    - name: Initialize database
      working-directory: ./server
      run: |
        # Run database initialization if needed
        PGPASSWORD=changeme psql -h localhost -U raguser -d ragdb -f init.sql || echo "Database already initialized"
      env:
        DATABASE_URL: postgresql+psycopg://raguser:changeme@localhost:5432/ragdb
        REDIS_URL: redis://:changeme@localhost:6379/0
        MINIO_ENDPOINT: localhost:9000
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
        MINIO_BUCKET: documents
        JWT_SECRET_KEY: test-secret-key-for-ci
        JWT_ALGORITHM: HS256
        JWT_EXPIRATION_MINUTES: 30
        OPENAI_API_KEY: test-openai-key
        APP_NAME: RAG RBAC CI
        DEBUG: true

    - name: Start FastAPI server in background
      working-directory: ./server
      run: |
        python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        echo $! > fastapi.pid
        # Wait for server to start
        sleep 10
        # Check if server is running
        curl -f http://localhost:8000/health || (echo "Server failed to start" && exit 1)
      env:
        DATABASE_URL: postgresql+psycopg://raguser:changeme@localhost:5432/ragdb
        REDIS_URL: redis://:changeme@localhost:6379/0
        MINIO_ENDPOINT: localhost:9000
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
        MINIO_BUCKET: documents
        JWT_SECRET_KEY: test-secret-key-for-ci
        JWT_ALGORITHM: HS256
        JWT_EXPIRATION_MINUTES: 30
        OPENAI_API_KEY: test-openai-key
        APP_NAME: RAG RBAC CI
        DEBUG: true

    - name: Run smoke tests
      working-directory: ./server
      run: |
        pytest tests/smoke/ -v --tb=short
      env:
        DATABASE_URL: postgresql+psycopg://raguser:changeme@localhost:5432/ragdb
        REDIS_URL: redis://:changeme@localhost:6379/0
        MINIO_ENDPOINT: localhost:9000
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
        MINIO_BUCKET: documents
        JWT_SECRET_KEY: test-secret-key-for-ci
        JWT_ALGORITHM: HS256
        JWT_EXPIRATION_MINUTES: 30
        OPENAI_API_KEY: test-openai-key
        APP_NAME: RAG RBAC CI
        DEBUG: true

    - name: Stop FastAPI server
      working-directory: ./server
      if: always()
      run: |
        if [ -f fastapi.pid ]; then
          kill $(cat fastapi.pid) || true
          rm fastapi.pid
        fi
